name: Create release on merge to main branch

on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: dexwritescode/release-on-merge-action@v1.1.0
        with:
          version-increment-strategy: minor
